#! /usr/bin/env bash
#
#   opengit [branch]
#
# This script will open your project's page on github.com.
#
# When no argument is passed, it will open the page on the current branch

# Fail on any error
set -eu

shopt -s extglob
# Open git URL using default 'open' ocommand
# $1: URL to open

function open_url()
{
  case $MACHTYPE in
    *apple*) local _open='open';;
    *linux*) local _open='xdg-open'
  esac
  echo "Running: $_open $1"
  $_open $1 &> /dev/null
}

# Check if remote is HTTPS or SSH
# If HTTPS, return everything after '.com/'
# If SSH, return everything after ':'

function get_remote()
{
  if ! remote=$(git config remote.origin.url); then
    echo "This is not a git repository" >&2
    return 1
  fi
  if [ -z "$remote" ]; then
    echo "There are no origin remote" >&2
    return 1
  fi
  if [ ${remote:0:4} = 'http' ]; then
    echo ${remote##*@(.org/|.com/)}
  elif [ ${remote:0:21} = 'ssh://git@git.konform' ]; then
    echo ${remote##*@(:7999/)}
  else
    echo ${remote##*:}
  fi
}

function get_repo() {
  echo ${remote##*@(/)}
}

function get_project() {
  echo ${remote%\/*}
}

# Check if the branch exists remotely
# $1: branch name (w/o remote)

function branch_exists()
{
  git branch -r|grep -q "origin/$1\$"
}

#
# Main
#
if ! remote=$(get_remote); then
  exit 1
# else
# 	echo "> [$remote]"
fi

if ! repo=$(get_repo); then
  exit 1
# else
# 	echo "> [$repo]"
fi

if ! project=$(get_project); then
  exit 1
# else
# 	echo "> [$project]"
fi


# Specify the service to be used
function url()
{
  if [[ $(git config remote.origin.url) =~ "github" ]]; then
    echo "https://github.com/${repo%.*}/tree/"
  fi

  if [[ $(git config remote.origin.url) =~ "bitbucket" ]]; then
    echo "https://bitbucket.org/${repo%%.*}/branch/"
  fi

  if [[ $(git config remote.origin.url) =~ "gitlab" ]]; then
    echo "https://gitlab.com/${repo%.*}/tree/"
  fi

  if [[ $(git config remote.origin.url) =~ "konform" ]]; then
    # https://git.konform.com/projects/KONFORM/repos/cms-5/pull-requests?create&sourceBranch=refs%2Fheads%2Fbugfix%2FCMS-129
    # https://git.konform.com/projects/KONFORM/repos/cms-5/browse?at=refs/heads/bugfix/CMS-129
    # https://git.konform.com/projects/KONFORM/repos/cms-5/pull-requests?create&sourceBranch=refs/heads/bugfix/CMS-129
    echo "https://git.konform.com/projects/${project}/repos/${repo%.*}/pull-requests?create&sourceBranch=refs/heads/"
    # echo "https://gitlab.com/${repo%.*}/tree/"
  fi
}

if [ $# -gt 0 ]; then
  branch=$1
else
  branch=$(git rev-parse --abbrev-ref HEAD)
fi

if ! branch_exists $branch; then
  echo "Branch $branch does not exists on remote"
  exit 1
fi

open_url $(url)$branch
